name: nglod
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - numpy
  - cudatoolkit
  - pytorch
  - torchvision
  - openexr-python
  - pip
  - pip:
    - pysdf
    - mesh2sdf
    - pymeshlab
    - pyrender
    - tensorboard
    - matplotlib
    - git+https://github.com/tinyobjloader/tinyobjloader.git
    - pybind11
    - trimesh
    - tqdm
    - Pillow
    - scipy
    - scikit-image
    - six
    - moviepy
    - opencv-python
    - plyfile
    - polyscope
